version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tony/fastapi-server:latest
    network_mode: host
    command: "gunicorn -b 0.0.0.0:${PORT} src.main:app -w ${WORKERS} -k uvicorn.workers.UvicornWorker --preload --log-level {LOGLEVEL}"
